service: marketplace-public-store
api_version: 1
runtime: python27
threadsafe: false
instance_class: F1

handlers:

- url: /public/store/assets
  static_dir: target/assets
  expiration: 1d

- url: /public/store/(.*\.(js|css|map))$
  static_files: target/\1
  upload: target/(.*\.(js|css|map))$
  expiration: 364d

- url: /.*
  static_files: target/index.html
  upload: target/index.html
  expiration: 1s
  secure: optional

skip_files:
- ^(?!target)
